name: m3_tomonokai
description: M3 Tomonokai feed
version: 1.0.0
homepage: https://github.com/niusounds/m3_tomonokai

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  html: ^0.15.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6
